// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDSDJWH3l0FrxMBh9NoYDkTAwVKJTB2ds',
    appId: '1:152964456413:web:5e092c3614572b4f2ea034',
    messagingSenderId: '152964456413',
    projectId: 'cj-flutter-bloc-todo-clean',
    authDomain: 'cj-flutter-bloc-todo-clean.firebaseapp.com',
    storageBucket: 'cj-flutter-bloc-todo-clean.appspot.com',
    measurementId: 'G-YYNH01VK8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi6MqOrQo78U-ytAoH5JfexW9uO0156Zk',
    appId: '1:152964456413:android:e751bd80d245aac12ea034',
    messagingSenderId: '152964456413',
    projectId: 'cj-flutter-bloc-todo-clean',
    storageBucket: 'cj-flutter-bloc-todo-clean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_HFRqSpKJq0uR27gP_ANnhvf2qWx79nw',
    appId: '1:152964456413:ios:bbb0636a896caca92ea034',
    messagingSenderId: '152964456413',
    projectId: 'cj-flutter-bloc-todo-clean',
    storageBucket: 'cj-flutter-bloc-todo-clean.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
